[package]
name = "book_service"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "app"
path = "src/bin/app.rs"

[[bin]]
name = "migration"
path = "src/bin/migration.rs"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.9"
envconfig = "0.11.1"
jiff = { version = "0.2.28", features = ["serde"] }
serde = "1.0.228"
toasty = { version = "0.7.0", features = ["postgresql", "migration", "jiff", "serde"] }
toasty-cli = "0.7.0"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.6.11", features = ["cors", "request-id", "timeout", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json"] }
uuid = { version = "1.23.2", features = ["v7", "fast-rng", "serde"] }
