export CARGO_TARGET_DIR := "../../target"

db_host := "localhost"
db_port := "5433"

# List available commands
help:
    @just --list --unsorted --list-heading $'📖BOOK-SERVICE\n'

# Run lints (cargo fmt and clippy)
lint:
    cargo +nightly fmt --package book_service -- --check
    cargo clippy --all-targets -- -D warnings

# Run cargo check
check:
    cargo check

# Run cargo build
build:
    cargo build --all-targets

# Run cargo clean on the book_service package
clean:
    cargo clean --package book_service

# Run cargo test
test:
    cargo test

# Run DB migrate
migration *cmd:
    @export $(grep -v '^#' .env | xargs) && \
    DB_HOST={{ db_host }} DB_PORT={{ db_port }} \
    cargo run --bin migration -- migration {{cmd}}

## =========================================================================
docker *cmd:
    docker {{cmd}}

build-for-prod:
    docker build --build-context workspace_root=../../ -t book-service-app -f prod.Dockerfile .